const scripts = {
    EN: {
        Title: 'Finish signing up',
        FirstName: 'First name',
        LastName: 'Last name',
        FirstNameRequired: 'First name is required',
        LastNameRequired: 'Last name is required',
        Email: 'Email address',
        EmailUse: 'We\'ll use your email address to send you updates',
        EmailRequired: 'Email is required',
        EmailHasInvalidFormat: 'Email has invalid format',
        Password: 'Password',
        PasswordRequired: 'Password must be 6 characters or more',
        Username: 'Username',
        UsernameRequired: 'Please provide a username with at least 4 characters',
        Location: 'Location',
        LocationUse: 'We\'ll use your location to show Mannam events near you.',
        Age: 'Age',
        AgeLimitation: 'Mannam members and organizers must be at least 18 years old.',
        Overage: 'I am 18 years of age or older.',
        SignUp: 'Sign up',
        Policy: 'By signing up, you agree to Terms of Service, Privacy Policy, and Cookie Policy.',
        AlreadyMember: 'Already a Member?',
        LogIn: 'Log in',
        SignUpError: 'There was an error signing you up, please try again',
    },
    KR: {
        Title: '회원 가입',
        FirstName: '이름',
        LastName: '성',
        FirstNameRequired: '이름은 필수입니다',
        LastNameRequired: '성은 필수입니다',
        Email: '이메일 주소',
        EmailUse: '이메일 주소를 통해 최신 소식을 보내드립니다',
        EmailRequired: '이메일은 필수입니다',
        EmailHasInvalidFormat: '이메일 형식이 맞지 않습니다',
        Password: '패스워드',
        PasswordRequired: '패스워드는 6자 이상으로 입력해주세요',
        Username: '유저네임',
        UsernameRequired: '유저네임은 4자 이상으로 입력해주세요',
        Location: '지역',
        LocationUse: '입력하신 주소를 사용하여 근처 Mannam 이벤트를 보여드립니다',
        Age: '나이',
        AgeLimitation: '18세 이하 분들은 Mannam 회원 가입이 불가능합니다',
        Overage: '18세 이상입니다',
        SignUp: '가입',
        Policy: '가입과 함께 서비스 규정, 개인정보 정책 및 쿠키 정책에 동의하신 것으로 간주됩니다',
        AlreadyMember: '이미 회원이십니까?',
        LogIn: '로그인',
        SignUpError: '회원가입에 문제가 발생하였습니다. 잠시 후 다시 시도하여 주세요',
    },
}

export default scripts
