const scripts = {
    EN: {
        Required: 'Required',
        TryAdding: 'Try adding a bit more to your name.',
        PleaseWrite: 'Please write at least 50 characters',
        InPerson: 'In Person',
        Online: 'Online',
        Public: 'Public',
        Private: 'Private',
        Success: 'Successfully modified',
        Failed: 'Something went wrong',
        Modify: 'Modify',
        Cancel: 'Cancel',
        Submit: 'Submit',
        GroupSettings: 'Group Settings',
        Name: 'Name',
        About: 'About',
        PublicTitle: 'Public?',
        Type: 'Type',
        City: 'City',
        State: 'State',
        GroupImages: 'Group images',
        Remove: 'Remove',
        AddGroupImage: '+ Add a group image',
        CancelAddImage: '- Cancel adding a group image',
        Add: '+ Add',
        CloseGroup: 'Close This Group',
    },
    KR: {
        Required: '필수입니다',
        TryAdding: '조금 더 길게 정해주세요.',
        PleaseWrite: '50자 이상으로 작성해주세요',
        InPerson: '오프라인 모임',
        Online: '온라인 모임',
        Success: '성공적으로 수정되었습니다.',
        Failed: '내용 수정에 실패하였습니다.',
        Modify: '수정',
        Cancel: '취소',
        Submit: '전송',
        GroupSettings: '그룹 설정',
        Name: '이름',
        About: '세부내용',
        PublicTitle: '공개여부',
        Public: '공개',
        Private: '비공개',
        Type: '종류',
        City: '도시',
        State: '주',
        GroupImages: '그룹 사진',
        Remove: '삭제',
        AddGroupImage: '+ 그룹 사진 추가',
        CancelAddImage: '- 그룹 사진 추가 취소',
        Add: '추가',
        CloseGroup: '이 그룹 폐쇄',
    },
}

export default scripts
