const scripts = {
    EN: {
        NotOrganizer: 'Permission denied',
        NeedVenues: 'Venues reqruied. Please create one from group setting page.',
        EventSettings: 'Event Settings',
        NoEvent: 'Currently, there\'s no events.',
        CreateEvent: '+ Create an event',
        CancelCreateEvent: '- Cancel creating an event',
        Required: 'Required',
        NameTooShort: 'Name should be more than 5 characters.',
        CapacityInteger: 'Capacity should be a positive integer.',
        PriceError: 'Price should be a number larger than or equal to 0.',
        DescError: 'Description should be more or equal to 50 characters',
        StartDateError: 'Start Date should be in future.',
        EndDateError: 'End Date should be furthur than Start Date',
        Name: 'Name',
        Type: 'Type',
        Capacity: 'Capacity',
        Price: 'Price',
        Desc: 'Description',
        StartDate: 'Start Date',
        EndDate: 'End Date',
        Venue: 'Venue',
        InPerson: 'In person',
        Online: 'Online',
        Submit: 'Submit',
        ChooseOne: 'Choose one of the options',
        ChooseVenue: 'You should choose a venue'
    },
    KR: {
        NotOrganizer: '권한이 없습니다',
        NeedVenues: '이벤트 장소가 필요합니다. 그룹 세팅 페이지에서 만들어 보세요.',
        EventSettings: '이벤트 세팅',
        NoEvent: '이벤트가 없습니다.',
        CreateEvent: '+ 이벤트 생성',
        CancelCreateEvent: '- 이벤트 생성 취소',
        Required: '필수입니다.',
        NameTooShort: '이름은 5글자 이상이어야 합니다.',
        CapacityInteger: '최대 정원은 양의 정수여야 합니다.',
        PriceError: '금액은 0 이상의 수여야 합니다.',
        StartDateError: '시작 일자는 현재보다 미래여야 합니다.',
        EndDateError: '종료 일자는 시작 일자보다 미래여야 합니다.',
        Name: '이벤트명',
        Type: '타입',
        Capacity: '최대 정원',
        Price: '가격',
        Desc: '설명',
        StartDate: '시작일시',
        EndDate: '종료일시',
        Venue: '장소',
        InPerson: '오프라인',
        Online: '온라인',
        DescError: '50자 이상이어야 합니다.',
        Submit: '전송',
        ChooseOne: '하나를 선택해주세요',
        ChooseVenue: '장소를 선택해주세요'
    }
}

export default scripts
