const scripts = {
    EN: {
        CreateGroup: 'Create your own Mannam group.',
        GetStarted: 'Get Started',
        YourAccount: 'Your Account',
        Settings: 'Settings',
        LogOut: 'Log out',
        LogIn: 'Log in',
        Help: 'Help',
        BecomeAffiliate: 'Becom an Affiliate',
        Discover: 'Discover',
        Groups: 'Groups',
        Calendar: 'Calendar',
        Topics: 'Topics',
        Cities: 'Cities',
        OnlineEvents: 'Online Events',
        LocalGuides: 'Local Guides',
        Mannam: 'Mannam',
        About: 'About',
        Blog: 'Blog',
        MannamPro: 'Mannam Pro',
        Careers: 'Careers',
        Apps: 'Apps',
        Podcast: 'Podcast',
        Terms: 'Terms of Service',
        Privacy: 'Privacy Policy'
    },
    KR: {
        CreateGroup: '직접 Mannam 그룹을 생성하세요.',
        GetStarted: '시작하기',
        YourAccount: '내 계정',
        Settings: '설정',
        LogOut: '로그아웃',
        LogIn: '로그인',
        Help: '도움말',
        BecomeAffiliate: '제휴사 되기',
        Discover: '발견',
        Groups: '그룹',
        Calendar: '달력',
        Topics: '주제',
        Cities: '도시',
        OnlineEvents: '온라인 이벤트',
        LocalGuides: '지역 가이드',
        Mannam: 'Mannam',
        About: '정보',
        Blog: '블로그',
        MannamPro: 'Mannam Pro',
        Careers: '커리어',
        Apps: '앱',
        Podcast: '팟캐스트',
        Terms: '서비스 약관',
        Privacy: '개인정보 보호정책'
    },
}

export default scripts
