const scripts = {
    EN: {
        Step: 'STEP',
        Of: 'OF',
        Next: 'Next',
        Back: 'Back',
        Submit: 'Submit',
        First: 'First, set your group\'s location.',
        MannamGroups: 'Mannam groups meet locally, in person and online. We\'ll connect you with people in your area, and more can join you online.',
        ChangeLocation: 'Change location',
        WhatWill: 'What will your group\'s name be?',
        ChooseName: 'Choose a name that will give people a clear idea of what the group is about. Feel free to get creative! You can edit this later if you change your mind.',
        Required: 'Required',
        TryAdding: 'Try adding a bit more to your name.',
        NowDescribe: 'Now describe what',
        WillBeAbout: ' will be about',
        PeopleWill: 'People will see this when we promote your group, but you\'ll be able to add to it later, too.',
        WhatPurpose: 'What\'s the purpose of the group?',
        WhoShould: 'Who should join?',
        WhatWillYou: 'What will you do at your events?',
        PleaseWrite: 'Please write at least 50 characters',
        AlmostDone: 'Almost done! Now choose your group type!',
        InPerson: 'In Person',
        Online: 'Online',
        Public: 'Public',
        Private: 'Private',
        Success: 'Successfully created',
        Failed: 'Something went wrong'
    },
    KR: {
        Step: '단계',
        Of: '/',
        Next: '다음',
        Back: '전 단계',
        Submit: '완료',
        First: '처음으로, 그룹의 위치를 정합니다.',
        MannamGroups: 'Mannam 그룹에서는 온라인으로 만나거나 해당 지역에서 직접 만납니다. 현재 지역의 사람들과 만나거나 온라인으로 만날 수 있도록 도와드립니다.',
        ChangeLocation: '위치 변경',
        WhatWill: '그룹명을 정해주세요.',
        ChooseName: '사람들에게 어떤 그룹인지 명확하게 알 수 있을만한 이름을 정해주세요. 추후 변경도 가능하오니 창의성을 발휘하여 멋지게 지어주세요!',
        Required: '필수입니다',
        TryAdding: '조금 더 길게 정해주세요.',
        NowDescribe: '이제',
        WillBeAbout: '가 어떤 그룹인지 설명해주세요.',
        PeopleWill: '이 그룹이 홍보될 때, 이 문구가 보일 것입니다. 추후 변경 가능합니다.',
        WhatPurpose: '이 그룹의 목적이 무엇인지?',
        WhoShould: '누가 이 그룹에 가입하면 좋을지?',
        WhatWillYou: '어떤 이벤트가 진행될 것인지?',
        PleaseWrite: '50자 이상으로 작성해주세요',
        AlmostDone: '거의 다 됐습니다! 이제 어떤 그룹 방식으로 하고 싶으신지 정하세요!',
        InPerson: '오프라인 모임',
        Online: '온라인 모임',
        Public: '공개',
        Private: '비공개',
        Success: '성공적으로 생성되었습니다.',
        Failed: '그룹 생성에 실패하였습니다.'
    }
}

export default scripts
